// CleanCentreReplyV31.gs
//
// V3.1 keeps the working V3 parent -> centre mirror threading, but replaces
// the centre -> parent GmailMessage.reply() hop. GmailMessage.reply() injects
// Gmail's automatic "On ... wrote:" quotation block. V3.1 sends a raw RFC 2822
// reply through the Gmail API instead, with explicit In-Reply-To / References
// headers and the existing Workspace threadId. The parent therefore keeps the
// same Gmail conversation while seeing only the centre's actual message body.
//
// Dependencies already used by V3:
//   - Code.gs
//   - ScannerV2.gs
//   - ThreadedRelayV3.gs
//   - Apps Script Gmail API advanced service (v1)

const ST_RELAY_V31_VERSION = '2026-08-14-threaded-v3.1-clean-centre-reply';

function runReplyRelayV31() {
  const cfg = relayConfig_();
  const processedList = loadProcessedIds_();
  const processed = new Set(processedList);

  const queries = [
    `in:inbox newer_than:${cfg.lookbackDays}d to:(${cfg.relayDomain})`,
    `in:inbox newer_than:${cfg.lookbackDays}d from:successtutoring.com.au`,
    `in:inbox newer_than:${cfg.lookbackDays}d from:successtutoring.com`,
  ];

  const threadsById = new Map();
  queries.forEach((query) => {
    GmailApp.search(query, 0, cfg.maxThreads).forEach((thread) => {
      threadsById.set(thread.getId(), thread);
    });
  });

  const messagesById = new Map();
  Array.from(threadsById.values()).forEach((thread) => {
    thread.getMessages().forEach((message) => messagesById.set(message.getId(), message));
  });

  const messages = Array.from(messagesById.values());
  messages.sort((a, b) => a.getDate().getTime() - b.getDate().getTime());

  console.log(`Reply relay V3.1 scan: ${threadsById.size} threads, ${messages.length} messages.`);

  let changed = false;
  messages.forEach((message) => {
    const messageId = message.getId();
    if (processed.has(messageId)) return;

    const sender = extractAddress_(message.getFrom());
    let relayToken = relayTokenFromMessage_(message, cfg.relayDomain);
    let conversation = null;

    try {
      if (relayToken) {
        conversation = lookupConversation_(cfg, relayToken);
      } else {
        if (!isPotentialCentreSender_(sender)) return;
        const route = relayRouteFromMessage_(message, cfg.relayDomain) || relayRouteFromSender_(sender);
        if (!route) return;
        conversation = lookupCentreConversationFallback_(cfg, route, sender, message.getSubject());
        relayToken = String(conversation.relayToken || '');
        if (!relayToken) throw new Error('Fallback relay lookup did not return a relay token.');
        console.log(`V3.1 recovered centre reply ${messageId} using route ${route}.`);
      }

      const centreInbox = String(conversation.centreInbox || '').toLowerCase();
      const fromAlias = String(conversation.fromAddress || '').toLowerCase();

      // Same loop protection as V2/V3. Messages generated by the Workspace
      // alias are never fed back through the relay scanner.
      if (sender && sender === fromAlias) {
        rememberProcessed_(processedList, processed, messageId);
        changed = true;
        return;
      }

      if (centreInbox && sender === centreInbox) {
        console.log(`V3.1 relaying centre reply ${messageId} cleanly to ${conversation.parentEmail}.`);
        handleCentreReplyCleanV31_(cfg, relayToken, conversation, message);
      } else {
        // Parent -> centre remains the proven V3 mirror-thread implementation.
        handleParentReplyThreadedV3_(cfg, relayToken, conversation, message);
      }

      rememberProcessed_(processedList, processed, messageId);
      changed = true;
    } catch (error) {
      console.error(`Reply relay V3.1 failed for Gmail message ${messageId}: ${error && error.stack ? error.stack : error}`);
      // Leave failed messages unprocessed so the next trigger can retry.
    }
  });

  if (changed) saveProcessedIds_(processedList);
}

function handleCentreReplyCleanV31_(cfg, relayToken, conversation, message) {
  const sender = extractAddress_(message.getFrom());
  const expected = String(conversation.centreInbox || '').toLowerCase();
  if (!expected || sender !== expected) {
    throw new Error(`Centre reply sender ${sender || '(unknown)'} does not match ${expected || '(missing centre inbox)'}.`);
  }

  const delivered = deliverCentreReplyCleanV31_(cfg, relayToken, conversation, message);

  postRelayEvent_(cfg, {
    eventType: 'centre_reply',
    relayToken,
    conversationId: conversation.conversationId,
    campusKey: conversation.campusKey,
    campusName: conversation.campusName,
    direction: 'centre_to_parent',
    actorRole: 'centre',
    actorName: conversation.fromName || conversation.campusName || displayNameFromHeader_(message.getFrom()),
    fromAddress: conversation.fromAddress,
    toAddress: conversation.parentEmail,
    subjectLine: conversation.subjectLine || delivered.subject,
    messageText: delivered.body,
    gmailMessageId: delivered.gmailMessageId,
    gmailThreadId: delivered.gmailThreadId,
    sourceMessageId: message.getId(),
    sendStatus: 'sent_to_parent',
    attachmentNames: delivered.attachmentNames,
    timestamp: new Date().toISOString(),
  });
}

function deliverCentreReplyCleanV31_(cfg, relayToken, conversation, message) {
  verifyGmailAdvancedServiceV3_();

  const parentMessage = findParentRelayMessageV2_(conversation);
  const parentAddress = extractAddress_(parentMessage.getFrom());
  const expectedParent = String(conversation.parentEmail || '').toLowerCase();
  if (!expectedParent || parentAddress !== expectedParent) {
    throw new Error(`Parent message sender ${parentAddress || '(unknown)'} does not match ${expectedParent || '(missing parent email)'}.`);
  }

  const body = cleanReplyBodyV3_(message.getPlainBody());
  if (!body) throw new Error('The centre reply did not contain any new message text.');

  const attachments = message.getAttachments({ includeInlineImages: false, includeAttachments: true });
  const attachmentNames = attachments.map((file) => file.getName());
  const relayAddress = `reply+${relayToken}@${cfg.relayDomain}`;

  // The RFC Message-ID of the exact parent message is the relationship anchor
  // that recipient Gmail uses to keep this reply in the parent's conversation.
  const parentInternetMessageId = internetMessageIdForGmailMessageV3_(parentMessage.getId());
  if (!parentInternetMessageId) {
    throw new Error('The parent reply is missing an RFC Message-ID, so a safe threaded reply cannot be created.');
  }

  const gmailThreadId = parentMessage.getThread().getId();
  const subject = centreToParentSubjectV31_(parentMessage, conversation);

  const sent = sendRawCentreReplyV31_({
    fromAddress: conversation.fromAddress,
    fromName: conversation.fromName || conversation.campusName || 'Success Tutoring',
    toAddress: conversation.parentEmail,
    replyTo: relayAddress,
    subject,
    body,
    inReplyTo: parentInternetMessageId,
    references: parentInternetMessageId,
    threadId: gmailThreadId,
    attachments,
  });

  return {
    body,
    attachmentNames,
    subject,
    gmailMessageId: String(sent.id || ''),
    gmailThreadId: String(sent.threadId || gmailThreadId || ''),
  };
}

function centreToParentSubjectV31_(parentMessage, conversation) {
  // Use the exact subject of the incoming parent message when available because
  // Gmail's API requires the subject to match when a message is added to an
  // existing Workspace thread. Fall back to one clean Re: prefix.
  const incoming = safeHeaderV3_(parentMessage && parentMessage.getSubject ? parentMessage.getSubject() : '');
  if (incoming) return incoming.slice(0, 250);
  return `Re: ${baseSubjectV3_(conversation.subjectLine || 'Feedback')}`.slice(0, 250);
}

function sendRawCentreReplyV31_(options) {
  verifyGmailAdvancedServiceV3_();
  assertSenderAliasV3_(options.fromAddress);

  const rawMime = buildRawMimeV3_(options);
  const encoded = Utilities.base64EncodeWebSafe(rawMime, Utilities.Charset.UTF_8).replace(/=+$/g, '');
  const request = { raw: encoded };
  if (options.threadId) request.threadId = String(options.threadId);

  const sent = Gmail.Users.Messages.send(request, 'me');
  if (!sent || !sent.id) throw new Error('Gmail API did not return a sent message id for the centre reply.');
  return sent;
}

function runReplyRelayV31FastA() {
  runReplyRelayV31Locked_('A');
}

function runReplyRelayV31FastB() {
  runReplyRelayV31Locked_('B');
}

function runReplyRelayV31Locked_(source) {
  const lock = LockService.getScriptLock();
  if (!lock.tryLock(3000)) {
    console.log(`Relay V3.1 ${source}: skipped because another scan is running.`);
    return;
  }
  const startedAt = Date.now();
  try {
    runReplyRelayV31();
    console.log(`Relay V3.1 ${source}: completed in ${Date.now() - startedAt}ms.`);
  } finally {
    lock.releaseLock();
  }
}

function verifyCleanCentreReplyV31() {
  verifyGmailAdvancedServiceV3_();

  if (typeof handleParentReplyThreadedV3_ !== 'function' ||
      typeof findParentRelayMessageV2_ !== 'function' ||
      typeof buildRawMimeV3_ !== 'function') {
    throw new Error('V3.1 dependencies are missing. Keep Code.gs, ScannerV2.gs and ThreadedRelayV3.gs installed and up to date.');
  }

  const parentId = '<parent-test@example.com>';
  const raw = buildRawMimeV3_({
    fromAddress: 'parramatta@st-feedback.site',
    fromName: 'Parramatta Success Tutoring',
    toAddress: 'parent@example.com',
    replyTo: 'reply+parramatta-test@st-feedback.site',
    subject: 'Re: Kevin – English • Book Reviews',
    body: 'All goods',
    inReplyTo: parentId,
    references: parentId,
    attachments: [],
  });

  if (!/In-Reply-To: <parent-test@example\.com>/i.test(raw) ||
      !/References: <parent-test@example\.com>/i.test(raw)) {
    throw new Error('V3.1 MIME reply headers self-test failed.');
  }

  const cleaned = cleanReplyBodyV3_(
    'All goods\n\nOn Fri, 14 Aug 2026 at 11:02 pm Kevin Abu via Parramatta Success Tutoring\n<parramatta@st-feedback.site> wrote:\n> Parent reply'
  );
  if (cleaned !== 'All goods') {
    throw new Error(`V3.1 centre reply cleaner self-test failed: ${cleaned}`);
  }

  console.log(JSON.stringify({
    ok: true,
    version: ST_RELAY_V31_VERSION,
    gmailApi: true,
    parentToCentreThreading: 'V3 unchanged',
    centreToParentMode: 'raw MIME reply; no Gmail auto-quote',
    cleanCentreReplySample: cleaned,
    aliases: GmailApp.getAliases(),
  }, null, 2));
}

function installFastRelayTriggersV31() {
  verifyCleanCentreReplyV31();

  ScriptApp.getProjectTriggers()
    .filter((trigger) => /^runReplyRelay/.test(trigger.getHandlerFunction()))
    .forEach((trigger) => ScriptApp.deleteTrigger(trigger));

  ScriptApp.newTrigger('runReplyRelayV31FastA').timeBased().everyMinutes(1).create();
  Utilities.sleep(15000);
  ScriptApp.newTrigger('runReplyRelayV31FastB').timeBased().everyMinutes(1).create();

  console.log(`Installed two locked V3.1 one-minute relay triggers. Version ${ST_RELAY_V31_VERSION}.`);
}

function showRelayTriggersV31() {
  console.log(JSON.stringify({
    version: ST_RELAY_V31_VERSION,
    triggers: ScriptApp.getProjectTriggers().map((trigger) => ({
      functionName: trigger.getHandlerFunction(),
      source: String(trigger.getTriggerSource()),
    })),
  }, null, 2));
}
