const PROCESSED_PROPERTY = 'ST_REPLY_RELAY_PROCESSED_IDS';
const MAX_PROCESSED_IDS = 1500;

function relayConfig_() {
  const props = PropertiesService.getScriptProperties();
  const baseUrl = String(props.getProperty('WEBHOOK_BASE_URL') || '').replace(/\/+$/, '');
  const secret = String(props.getProperty('WEBHOOK_SECRET') || '');
  const relayDomain = String(props.getProperty('RELAY_DOMAIN') || 'st-feedback.site').toLowerCase().replace(/^@+/, '');
  const lookbackDays = Math.max(1, Math.min(30, Number(props.getProperty('LOOKBACK_DAYS') || 7)));
  const maxThreads = Math.max(10, Math.min(250, Number(props.getProperty('MAX_THREADS') || 100)));
  if (!baseUrl || !secret) throw new Error('Set WEBHOOK_BASE_URL and WEBHOOK_SECRET in Apps Script > Project Settings > Script Properties.');
  return { baseUrl, secret, relayDomain, lookbackDays, maxThreads };
}

function runReplyRelay() {
  const cfg = relayConfig_();
  const processedList = loadProcessedIds_();
  const processed = new Set(processedList);
  const query = `in:inbox newer_than:${cfg.lookbackDays}d to:(${cfg.relayDomain})`;
  const threads = GmailApp.search(query, 0, cfg.maxThreads);
  const messages = [];

  threads.forEach((thread) => {
    thread.getMessages().forEach((message) => messages.push(message));
  });
  messages.sort((a, b) => a.getDate().getTime() - b.getDate().getTime());

  let changed = false;
  messages.forEach((message) => {
    const messageId = message.getId();
    if (processed.has(messageId)) return;

    const sender = extractAddress_(message.getFrom());
    let relayToken = relayTokenFromMessage_(message, cfg.relayDomain);
    let conversation = null;

    try {
      if (relayToken) {
        conversation = lookupConversation_(cfg, relayToken);
      } else {
        // Some centre mail systems ignore Reply-To and respond to the visible
        // centre alias instead. Only attempt a fallback for approved-looking
        // Success Tutoring senders, then require an exact unique centre inbox +
        // subject match on the centre deployment before relaying anything.
        if (!isPotentialCentreSender_(sender)) return;
        const route = relayRouteFromMessage_(message, cfg.relayDomain) || relayRouteFromSender_(sender);
        if (!route) return;
        conversation = lookupCentreConversationFallback_(cfg, route, sender, message.getSubject());
        relayToken = String(conversation.relayToken || '');
        if (!relayToken) throw new Error('Fallback relay lookup did not return a relay token.');
        console.log(`Recovered centre reply without reply+ recipient using route ${route}.`);
      }

      const centreInbox = String(conversation.centreInbox || '').toLowerCase();
      const fromAlias = String(conversation.fromAddress || '').toLowerCase();

      // Never relay mail generated by the Workspace alias itself; this avoids
      // loops if Gmail places an internally-routed message back in the inbox.
      if (sender && sender === fromAlias) {
        rememberProcessed_(processedList, processed, messageId);
        changed = true;
        return;
      }

      if (centreInbox && sender === centreInbox) {
        handleCentreReply_(cfg, relayToken, conversation, message);
      } else {
        handleParentReply_(cfg, relayToken, conversation, message);
      }

      rememberProcessed_(processedList, processed, messageId);
      changed = true;
    } catch (error) {
      console.error(`Reply relay failed for Gmail message ${messageId}: ${error && error.stack ? error.stack : error}`);
      // Leave the message unprocessed so the next trigger run can retry it.
    }
  });

  if (changed) saveProcessedIds_(processedList);
}

function handleParentReply_(cfg, relayToken, conversation, message) {
  const sender = extractAddress_(message.getFrom());
  if (!sender) throw new Error('Parent reply sender address could not be read.');
  if (!conversation.centreInbox) throw new Error('The centre forwarding inbox is missing for this conversation.');

  const relayAddress = `reply+${relayToken}@${cfg.relayDomain}`;
  const body = cleanIncomingBody_(message.getPlainBody());
  const thread = message.getThread();
  const attachments = message.getAttachments({ includeInlineImages: false, includeAttachments: true });
  const attachmentNames = attachments.map((file) => file.getName());

  postRelayEvent_(cfg, {
    eventType: 'parent_reply',
    relayToken,
    conversationId: conversation.conversationId,
    campusKey: conversation.campusKey,
    campusName: conversation.campusName,
    direction: 'parent_to_centre',
    actorRole: 'parent',
    actorName: displayNameFromHeader_(message.getFrom()),
    fromAddress: sender,
    toAddress: conversation.centreInbox,
    subjectLine: message.getSubject(),
    messageText: body,
    gmailMessageId: message.getId(),
    gmailThreadId: thread.getId(),
    sourceMessageId: message.getId(),
    sendStatus: 'received_and_forwarded',
    attachmentNames,
    timestamp: message.getDate().toISOString(),
  });

  // Send the centre a clean notification rather than a raw forward. Reply-To
  // still points at the unique relay address, and the subject also carries the
  // token as a fallback for mail systems that ignore Reply-To.
  const centreSubject = centreRelaySubject_(message.getSubject(), relayToken);
  const centreBody = centreRelayBody_(conversation, message, body);
  GmailApp.sendEmail(
    conversation.centreInbox,
    centreSubject,
    centreBody,
    gmailSendOptions_(conversation.fromAddress, conversation.fromName || conversation.campusName || 'Success Tutoring', relayAddress, attachments),
  );
}

function handleCentreReply_(cfg, relayToken, conversation, message) {
  const sender = extractAddress_(message.getFrom());
  const expected = String(conversation.centreInbox || '').toLowerCase();
  if (!expected || sender !== expected) {
    throw new Error(`Centre reply sender ${sender || '(unknown)'} does not match ${expected || '(missing centre inbox)'}.`);
  }
  if (!conversation.gmailThreadId) {
    throw new Error('No parent Gmail thread is recorded yet for this relay conversation.');
  }

  const thread = GmailApp.getThreadById(conversation.gmailThreadId);
  if (!thread) throw new Error('The original parent Gmail thread could not be found.');

  const relayAddress = `reply+${relayToken}@${cfg.relayDomain}`;
  const body = cleanIncomingBody_(message.getPlainBody());
  if (!body) throw new Error('The centre reply did not contain any new message text.');

  const attachments = message.getAttachments({ includeInlineImages: false, includeAttachments: true });
  thread.reply(
    body,
    gmailSendOptions_(conversation.fromAddress, conversation.fromName || conversation.campusName || 'Success Tutoring', relayAddress, attachments),
  );

  // Read back the message Gmail just added to the original parent thread so
  // the portal can store the actual Gmail message id.
  const refreshed = GmailApp.getThreadById(conversation.gmailThreadId);
  const sentMessages = refreshed ? refreshed.getMessages() : [];
  const sentMessage = sentMessages.length ? sentMessages[sentMessages.length - 1] : null;
  const attachmentNames = attachments.map((file) => file.getName());

  postRelayEvent_(cfg, {
    eventType: 'centre_reply',
    relayToken,
    conversationId: conversation.conversationId,
    campusKey: conversation.campusKey,
    campusName: conversation.campusName,
    direction: 'centre_to_parent',
    actorRole: 'centre',
    actorName: conversation.fromName || conversation.campusName || displayNameFromHeader_(message.getFrom()),
    fromAddress: conversation.fromAddress,
    toAddress: conversation.parentEmail,
    subjectLine: conversation.subjectLine || message.getSubject(),
    messageText: body,
    gmailMessageId: sentMessage ? sentMessage.getId() : message.getId(),
    gmailThreadId: conversation.gmailThreadId,
    sourceMessageId: message.getId(),
    sendStatus: 'sent_to_parent',
    attachmentNames,
    timestamp: new Date().toISOString(),
  });
}

function gmailSendOptions_(fromAddress, fromName, replyTo, attachments) {
  const options = {
    name: fromName || 'Success Tutoring',
    replyTo,
    attachments: attachments || [],
  };
  const from = String(fromAddress || '').toLowerCase();
  if (!from) return options;

  const primary = String(Session.getActiveUser().getEmail() || '').toLowerCase();
  if (from === primary) return options;

  const aliases = GmailApp.getAliases().map((address) => String(address || '').toLowerCase());
  if (!aliases.includes(from)) {
    throw new Error(`Configured sender ${from} is not available as a Gmail alias.`);
  }
  options.from = fromAddress;
  return options;
}

function centreRelaySubject_(subject, relayToken) {
  const tag = `[ST-RELAY:${relayToken}]`;
  const clean = String(subject || 'Parent feedback reply')
    .replace(/\[ST-RELAY:[^\]]+\]\s*/ig, '')
    .replace(/\s+/g, ' ')
    .trim();
  return `${tag} ${clean}`.slice(0, 250);
}

function centreRelayBody_(conversation, message, body) {
  const parentName = displayNameFromHeader_(message.getFrom()) || conversation.parentName || conversation.parentEmail || 'Parent';
  const subject = conversation.subjectLine || message.getSubject() || 'Feedback email';
  return [
    `${parentName} replied to the feedback email.`,
    '',
    body || '(No new message text was detected.)',
    '',
    '---',
    `Original subject: ${subject}`,
    '',
    'Reply normally to this email. Your response will be sent back to the parent from the centre feedback address and recorded in Sent Feedback.',
  ].join('\n');
}

function lookupConversation_(cfg, relayToken) {
  const url = `${cfg.baseUrl}/api/reply-relay-lookup?token=${encodeURIComponent(relayToken)}`;
  const response = UrlFetchApp.fetch(url, {
    method: 'get',
    muteHttpExceptions: true,
    headers: { 'x-st-relay-secret': cfg.secret },
  });
  const text = response.getContentText();
  let json = {};
  try { json = JSON.parse(text || '{}'); } catch (_) {}
  if (response.getResponseCode() !== 200 || !json.ok) {
    throw new Error(`Relay lookup failed (${response.getResponseCode()}): ${json.error || text}`);
  }
  return json;
}

function lookupCentreConversationFallback_(cfg, route, sender, subject) {
  const params = [
    `route=${encodeURIComponent(route)}`,
    `sender=${encodeURIComponent(sender)}`,
    `subject=${encodeURIComponent(subject || '')}`,
  ].join('&');
  const response = UrlFetchApp.fetch(`${cfg.baseUrl}/api/reply-relay-lookup?${params}`, {
    method: 'get',
    muteHttpExceptions: true,
    headers: { 'x-st-relay-secret': cfg.secret },
  });
  const text = response.getContentText();
  let json = {};
  try { json = JSON.parse(text || '{}'); } catch (_) {}
  if (response.getResponseCode() !== 200 || !json.ok) {
    throw new Error(`Fallback relay lookup failed (${response.getResponseCode()}): ${json.error || text}`);
  }
  return json;
}

function postRelayEvent_(cfg, payload) {
  const response = UrlFetchApp.fetch(`${cfg.baseUrl}/api/reply-relay-webhook`, {
    method: 'post',
    contentType: 'application/json',
    payload: JSON.stringify(payload),
    muteHttpExceptions: true,
    headers: { 'x-st-relay-secret': cfg.secret },
  });
  const text = response.getContentText();
  let json = {};
  try { json = JSON.parse(text || '{}'); } catch (_) {}
  if (response.getResponseCode() !== 200 || !json.ok) {
    throw new Error(`Relay webhook failed (${response.getResponseCode()}): ${json.error || text}`);
  }
  return json;
}

function relayTokenFromMessage_(message, relayDomain) {
  return relayTokenFromRecipients_(message, relayDomain) || relayTokenFromSubject_(message.getSubject());
}

function relayTokenFromRecipients_(message, relayDomain) {
  const recipients = `${message.getTo() || ''},${message.getCc() || ''}`;
  const escaped = relayDomain.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const match = recipients.match(new RegExp(`reply\\+([A-Za-z0-9_-]+)@${escaped}`, 'i'));
  return match ? match[1] : '';
}

function relayTokenFromSubject_(subject) {
  const match = String(subject || '').match(/\[ST-RELAY:([A-Za-z0-9_-]+)\]/i);
  return match ? match[1] : '';
}

function relayRouteFromMessage_(message, relayDomain) {
  const recipients = `${message.getTo() || ''},${message.getCc() || ''}`;
  const escaped = relayDomain.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`([A-Z0-9._%+\\-]+)@${escaped}`, 'ig');
  let match;
  while ((match = regex.exec(recipients))) {
    const local = String(match[1] || '').toLowerCase();
    if (!local || local.startsWith('reply+')) continue;
    return local.replace(/[^a-z0-9]+/g, '').slice(0, 20);
  }
  return '';
}

function relayRouteFromSender_(sender) {
  const local = String(sender || '').toLowerCase().split('@')[0] || '';
  return local.replace(/[^a-z0-9]+/g, '').slice(0, 20);
}

function isPotentialCentreSender_(sender) {
  return /@successtutoring\.com(?:\.au)?$/i.test(String(sender || '').trim());
}

function extractAddress_(header) {
  const value = String(header || '').trim();
  const bracket = value.match(/<([^<>\s]+@[^<>\s]+)>/);
  if (bracket) return bracket[1].toLowerCase();
  const plain = value.match(/([A-Z0-9._%+'-]+@[A-Z0-9.-]+\.[A-Z]{2,})/i);
  return plain ? plain[1].toLowerCase() : '';
}

function displayNameFromHeader_(header) {
  const value = String(header || '').trim();
  const bracketIndex = value.indexOf('<');
  if (bracketIndex > 0) return value.slice(0, bracketIndex).replace(/^"|"$/g, '').trim();
  return '';
}

function cleanIncomingBody_(rawBody) {
  let body = String(rawBody || '').replace(/\r\n/g, '\n').trim();
  if (!body) return '';

  const splitPatterns = [
    /\nOn [^\n]+wrote:\s*(?:\n|$)/i,
    /\n-{2,}\s*Original Message\s*-{2,}\s*\n/i,
    /\nFrom:\s*.+\nSent:\s*.+\nTo:\s*.+\nSubject:\s*.+\n/i,
    /\n_{5,}\s*\n/,
  ];
  for (const pattern of splitPatterns) {
    const parts = body.split(pattern);
    if (parts.length > 1 && parts[0].trim()) {
      body = parts[0].trim();
      break;
    }
  }

  body = body
    .split('\n')
    .filter((line) => !/^\s*>/.test(line))
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  return body;
}

function loadProcessedIds_() {
  const raw = PropertiesService.getScriptProperties().getProperty(PROCESSED_PROPERTY) || '[]';
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed.filter(Boolean).slice(-MAX_PROCESSED_IDS) : [];
  } catch (_) {
    return [];
  }
}

function rememberProcessed_(list, set, messageId) {
  if (!messageId || set.has(messageId)) return;
  list.push(messageId);
  set.add(messageId);
  while (list.length > MAX_PROCESSED_IDS) {
    const removed = list.shift();
    set.delete(removed);
  }
}

function saveProcessedIds_(ids) {
  PropertiesService.getScriptProperties().setProperty(PROCESSED_PROPERTY, JSON.stringify(ids.slice(-MAX_PROCESSED_IDS)));
}

function installMinuteTrigger() {
  ScriptApp.getProjectTriggers()
    .filter((trigger) => trigger.getHandlerFunction() === 'runReplyRelay')
    .forEach((trigger) => ScriptApp.deleteTrigger(trigger));
  ScriptApp.newTrigger('runReplyRelay').timeBased().everyMinutes(1).create();
  console.log('Installed 1-minute reply relay trigger.');
}

function testRelayConfiguration() {
  const cfg = relayConfig_();
  console.log(JSON.stringify({
    webhookBaseUrl: cfg.baseUrl,
    relayDomain: cfg.relayDomain,
    lookbackDays: cfg.lookbackDays,
    maxThreads: cfg.maxThreads,
    gmailAliases: GmailApp.getAliases(),
  }, null, 2));
}
