const PROCESSED_PROPERTY = 'ST_REPLY_RELAY_PROCESSED_IDS';
const MAX_PROCESSED_IDS = 1500;

function relayConfig_() {
  const props = PropertiesService.getScriptProperties();
  const baseUrl = String(props.getProperty('WEBHOOK_BASE_URL') || '').replace(/\/+$/, '');
  const secret = String(props.getProperty('WEBHOOK_SECRET') || '');
  const relayDomain = String(props.getProperty('RELAY_DOMAIN') || 'st-feedback.site').toLowerCase().replace(/^@+/, '');
  const lookbackDays = Math.max(1, Math.min(30, Number(props.getProperty('LOOKBACK_DAYS') || 7)));
  const maxThreads = Math.max(10, Math.min(250, Number(props.getProperty('MAX_THREADS') || 100)));
  if (!baseUrl || !secret) throw new Error('Set WEBHOOK_BASE_URL and WEBHOOK_SECRET in Apps Script > Project Settings > Script Properties.');
  return { baseUrl, secret, relayDomain, lookbackDays, maxThreads };
}

function runReplyRelay() {
  const cfg = relayConfig_();
  const processedList = loadProcessedIds_();
  const processed = new Set(processedList);
  const query = `in:inbox newer_than:${cfg.lookbackDays}d to:(${cfg.relayDomain})`;
  const threads = GmailApp.search(query, 0, cfg.maxThreads);
  const messages = [];

  threads.forEach((thread) => {
    thread.getMessages().forEach((message) => messages.push(message));
  });
  messages.sort((a, b) => a.getDate().getTime() - b.getDate().getTime());

  let changed = false;
  messages.forEach((message) => {
    const messageId = message.getId();
    if (processed.has(messageId)) return;

    const relayToken = relayTokenFromRecipients_(message, cfg.relayDomain);
    if (!relayToken) return;

    try {
      const conversation = lookupConversation_(cfg, relayToken);
      const sender = extractAddress_(message.getFrom());
      const centreInbox = String(conversation.centreInbox || '').toLowerCase();
      const fromAlias = String(conversation.fromAddress || '').toLowerCase();

      // Never relay mail generated by the Workspace alias itself; this avoids
      // loops if Gmail places an internally-routed message back in the inbox.
      if (sender && sender === fromAlias) {
        rememberProcessed_(processedList, processed, messageId);
        changed = true;
        return;
      }

      if (centreInbox && sender === centreInbox) {
        handleCentreReply_(cfg, relayToken, conversation, message);
      } else {
        handleParentReply_(cfg, relayToken, conversation, message);
      }

      rememberProcessed_(processedList, processed, messageId);
      changed = true;
    } catch (error) {
      console.error(`Reply relay failed for Gmail message ${messageId}: ${error && error.stack ? error.stack : error}`);
      // Leave the message unprocessed so the next trigger run can retry it.
    }
  });

  if (changed) saveProcessedIds_(processedList);
}

function handleParentReply_(cfg, relayToken, conversation, message) {
  const sender = extractAddress_(message.getFrom());
  if (!sender) throw new Error('Parent reply sender address could not be read.');
  if (!conversation.centreInbox) throw new Error('The centre forwarding inbox is missing for this conversation.');

  const relayAddress = `reply+${relayToken}@${cfg.relayDomain}`;
  const body = cleanIncomingBody_(message.getPlainBody());
  const thread = message.getThread();
  const attachmentNames = message.getAttachments({ includeInlineImages: false, includeAttachments: true }).map((file) => file.getName());

  postRelayEvent_(cfg, {
    eventType: 'parent_reply',
    relayToken,
    conversationId: conversation.conversationId,
    campusKey: conversation.campusKey,
    campusName: conversation.campusName,
    direction: 'parent_to_centre',
    actorRole: 'parent',
    actorName: displayNameFromHeader_(message.getFrom()),
    fromAddress: sender,
    toAddress: conversation.centreInbox,
    subjectLine: message.getSubject(),
    messageText: body,
    gmailMessageId: message.getId(),
    gmailThreadId: thread.getId(),
    sourceMessageId: message.getId(),
    sendStatus: 'received_and_forwarded',
    attachmentNames,
    timestamp: message.getDate().toISOString(),
  });

  // Forward a copy to the centre's normal Success Tutoring inbox. Staff can
  // simply hit Reply there; Reply-To points back to the unique relay address.
  message.forward(conversation.centreInbox, {
    from: conversation.fromAddress,
    name: conversation.fromName || conversation.campusName || 'Success Tutoring',
    replyTo: relayAddress,
  });
}

function handleCentreReply_(cfg, relayToken, conversation, message) {
  const sender = extractAddress_(message.getFrom());
  const expected = String(conversation.centreInbox || '').toLowerCase();
  if (!expected || sender !== expected) {
    throw new Error(`Centre reply sender ${sender || '(unknown)'} does not match ${expected || '(missing centre inbox)'}.`);
  }
  if (!conversation.gmailThreadId) {
    throw new Error('No parent Gmail thread is recorded yet for this relay conversation.');
  }

  const thread = GmailApp.getThreadById(conversation.gmailThreadId);
  if (!thread) throw new Error('The original parent Gmail thread could not be found.');

  const relayAddress = `reply+${relayToken}@${cfg.relayDomain}`;
  const body = cleanIncomingBody_(message.getPlainBody());
  if (!body) throw new Error('The centre reply did not contain any new message text.');

  const attachments = message.getAttachments({ includeInlineImages: false, includeAttachments: true });
  thread.reply(body, {
    from: conversation.fromAddress,
    name: conversation.fromName || conversation.campusName || 'Success Tutoring',
    replyTo: relayAddress,
    attachments,
  });

  // Read back the message Gmail just added to the original parent thread so
  // the portal can store the actual Gmail message id.
  const refreshed = GmailApp.getThreadById(conversation.gmailThreadId);
  const sentMessages = refreshed ? refreshed.getMessages() : [];
  const sentMessage = sentMessages.length ? sentMessages[sentMessages.length - 1] : null;
  const attachmentNames = attachments.map((file) => file.getName());

  postRelayEvent_(cfg, {
    eventType: 'centre_reply',
    relayToken,
    conversationId: conversation.conversationId,
    campusKey: conversation.campusKey,
    campusName: conversation.campusName,
    direction: 'centre_to_parent',
    actorRole: 'centre',
    actorName: conversation.fromName || conversation.campusName || displayNameFromHeader_(message.getFrom()),
    fromAddress: conversation.fromAddress,
    toAddress: conversation.parentEmail,
    subjectLine: conversation.subjectLine || message.getSubject(),
    messageText: body,
    gmailMessageId: sentMessage ? sentMessage.getId() : message.getId(),
    gmailThreadId: conversation.gmailThreadId,
    sourceMessageId: message.getId(),
    sendStatus: 'sent_to_parent',
    attachmentNames,
    timestamp: new Date().toISOString(),
  });
}

function lookupConversation_(cfg, relayToken) {
  const url = `${cfg.baseUrl}/api/reply-relay-lookup?token=${encodeURIComponent(relayToken)}`;
  const response = UrlFetchApp.fetch(url, {
    method: 'get',
    muteHttpExceptions: true,
    headers: { 'x-st-relay-secret': cfg.secret },
  });
  const text = response.getContentText();
  let json = {};
  try { json = JSON.parse(text || '{}'); } catch (_) {}
  if (response.getResponseCode() !== 200 || !json.ok) {
    throw new Error(`Relay lookup failed (${response.getResponseCode()}): ${json.error || text}`);
  }
  return json;
}

function postRelayEvent_(cfg, payload) {
  const response = UrlFetchApp.fetch(`${cfg.baseUrl}/api/reply-relay-webhook`, {
    method: 'post',
    contentType: 'application/json',
    payload: JSON.stringify(payload),
    muteHttpExceptions: true,
    headers: { 'x-st-relay-secret': cfg.secret },
  });
  const text = response.getContentText();
  let json = {};
  try { json = JSON.parse(text || '{}'); } catch (_) {}
  if (response.getResponseCode() !== 200 || !json.ok) {
    throw new Error(`Relay webhook failed (${response.getResponseCode()}): ${json.error || text}`);
  }
  return json;
}

function relayTokenFromRecipients_(message, relayDomain) {
  const recipients = `${message.getTo() || ''},${message.getCc() || ''}`;
  const escaped = relayDomain.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const match = recipients.match(new RegExp(`reply\\+([A-Za-z0-9_-]+)@${escaped}`, 'i'));
  return match ? match[1] : '';
}

function extractAddress_(header) {
  const value = String(header || '').trim();
  const bracket = value.match(/<([^<>\s]+@[^<>\s]+)>/);
  if (bracket) return bracket[1].toLowerCase();
  const plain = value.match(/([A-Z0-9._%+'-]+@[A-Z0-9.-]+\.[A-Z]{2,})/i);
  return plain ? plain[1].toLowerCase() : '';
}

function displayNameFromHeader_(header) {
  const value = String(header || '').trim();
  const bracketIndex = value.indexOf('<');
  if (bracketIndex > 0) return value.slice(0, bracketIndex).replace(/^"|"$/g, '').trim();
  return '';
}

function cleanIncomingBody_(rawBody) {
  let body = String(rawBody || '').replace(/\r\n/g, '\n').trim();
  if (!body) return '';

  const splitPatterns = [
    /\nOn .+ wrote:\s*\n/i,
    /\n-{2,}\s*Original Message\s*-{2,}\s*\n/i,
    /\nFrom:\s*.+\nSent:\s*.+\nTo:\s*.+\nSubject:\s*.+\n/i,
    /\n_{5,}\s*\n/,
  ];
  for (const pattern of splitPatterns) {
    const parts = body.split(pattern);
    if (parts.length > 1 && parts[0].trim()) {
      body = parts[0].trim();
      break;
    }
  }

  body = body
    .split('\n')
    .filter((line) => !/^\s*>/.test(line))
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  return body;
}

function loadProcessedIds_() {
  const raw = PropertiesService.getScriptProperties().getProperty(PROCESSED_PROPERTY) || '[]';
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed.filter(Boolean).slice(-MAX_PROCESSED_IDS) : [];
  } catch (_) {
    return [];
  }
}

function rememberProcessed_(list, set, messageId) {
  if (!messageId || set.has(messageId)) return;
  list.push(messageId);
  set.add(messageId);
  while (list.length > MAX_PROCESSED_IDS) {
    const removed = list.shift();
    set.delete(removed);
  }
}

function saveProcessedIds_(ids) {
  PropertiesService.getScriptProperties().setProperty(PROCESSED_PROPERTY, JSON.stringify(ids.slice(-MAX_PROCESSED_IDS)));
}

function installMinuteTrigger() {
  ScriptApp.getProjectTriggers()
    .filter((trigger) => trigger.getHandlerFunction() === 'runReplyRelay')
    .forEach((trigger) => ScriptApp.deleteTrigger(trigger));
  ScriptApp.newTrigger('runReplyRelay').timeBased().everyMinutes(1).create();
  console.log('Installed 1-minute reply relay trigger.');
}

function testRelayConfiguration() {
  const cfg = relayConfig_();
  console.log(JSON.stringify({
    webhookBaseUrl: cfg.baseUrl,
    relayDomain: cfg.relayDomain,
    lookbackDays: cfg.lookbackDays,
    maxThreads: cfg.maxThreads,
    gmailAliases: GmailApp.getAliases(),
  }, null, 2));
}
