// ThreadedRelayV3.gs
//
// V3 keeps the portal relay behaviour from V2, but makes the centre-facing
// Gmail experience a real conversation. On the first parent reply we create a
// centre-side mirror of the original feedback, then send every parent reply
// with RFC In-Reply-To / References headers pointing at that mirror.
//
// Dependency: Apps Script > Services > + > Gmail API (v1).

const ST_RELAY_V3_VERSION = '2026-08-14-threaded-v3.0';
const ST_RELAY_V3_MIRROR_PREFIX = 'ST_RELAY_V3_MIRROR_';
const ST_RELAY_V3_MIRROR_MAX_AGE_MS = 35 * 24 * 60 * 60 * 1000;

function runReplyRelayV3() {
  const cfg = relayConfig_();
  const processedList = loadProcessedIds_();
  const processed = new Set(processedList);

  const queries = [
    `in:inbox newer_than:${cfg.lookbackDays}d to:(${cfg.relayDomain})`,
    `in:inbox newer_than:${cfg.lookbackDays}d from:successtutoring.com.au`,
    `in:inbox newer_than:${cfg.lookbackDays}d from:successtutoring.com`,
  ];

  const threadsById = new Map();
  queries.forEach((query) => {
    GmailApp.search(query, 0, cfg.maxThreads).forEach((thread) => {
      threadsById.set(thread.getId(), thread);
    });
  });

  const messagesById = new Map();
  Array.from(threadsById.values()).forEach((thread) => {
    thread.getMessages().forEach((message) => messagesById.set(message.getId(), message));
  });

  const messages = Array.from(messagesById.values());
  messages.sort((a, b) => a.getDate().getTime() - b.getDate().getTime());

  console.log(`Reply relay V3 scan: ${threadsById.size} threads, ${messages.length} messages.`);

  let changed = false;
  messages.forEach((message) => {
    const messageId = message.getId();
    if (processed.has(messageId)) return;

    const sender = extractAddress_(message.getFrom());
    let relayToken = relayTokenFromMessage_(message, cfg.relayDomain);
    let conversation = null;

    try {
      if (relayToken) {
        conversation = lookupConversation_(cfg, relayToken);
      } else {
        if (!isPotentialCentreSender_(sender)) return;
        const route = relayRouteFromMessage_(message, cfg.relayDomain) || relayRouteFromSender_(sender);
        if (!route) return;
        conversation = lookupCentreConversationFallback_(cfg, route, sender, message.getSubject());
        relayToken = String(conversation.relayToken || '');
        if (!relayToken) throw new Error('Fallback relay lookup did not return a relay token.');
        console.log(`V3 recovered centre reply ${messageId} using route ${route}.`);
      }

      const centreInbox = String(conversation.centreInbox || '').toLowerCase();
      const fromAlias = String(conversation.fromAddress || '').toLowerCase();

      // Never relay messages generated by our own Workspace alias back into the
      // relay. This is the same loop protection used by V2.
      if (sender && sender === fromAlias) {
        rememberProcessed_(processedList, processed, messageId);
        changed = true;
        return;
      }

      if (centreInbox && sender === centreInbox) {
        handleCentreReplyV2_(cfg, relayToken, conversation, message);
      } else {
        handleParentReplyThreadedV3_(cfg, relayToken, conversation, message);
      }

      rememberProcessed_(processedList, processed, messageId);
      changed = true;
    } catch (error) {
      console.error(`Reply relay V3 failed for Gmail message ${messageId}: ${error && error.stack ? error.stack : error}`);
      // Leave it unprocessed so the next trigger can safely retry.
    }
  });

  if (changed) saveProcessedIds_(processedList);
}

function handleParentReplyThreadedV3_(cfg, relayToken, conversation, message) {
  const sender = extractAddress_(message.getFrom());
  if (!sender) throw new Error('Parent reply sender address could not be read.');
  if (!conversation.centreInbox) throw new Error('The centre forwarding inbox is missing for this conversation.');

  const expectedParent = String(conversation.parentEmail || '').toLowerCase();
  if (expectedParent && sender !== expectedParent) {
    throw new Error(`Unexpected parent reply sender ${sender}; expected ${expectedParent}.`);
  }

  const body = cleanReplyBodyV3_(message.getPlainBody());
  if (!body) throw new Error('The parent reply did not contain any new message text.');

  const relayAddress = `reply+${relayToken}@${cfg.relayDomain}`;
  const thread = message.getThread();
  const attachments = message.getAttachments({ includeInlineImages: false, includeAttachments: true });
  const attachmentNames = attachments.map((file) => file.getName());

  // Record the parent reply in the portal first. The webhook is idempotent, so
  // if centre delivery fails this Gmail message can retry without duplication.
  postRelayEvent_(cfg, {
    eventType: 'parent_reply',
    relayToken,
    conversationId: conversation.conversationId,
    campusKey: conversation.campusKey,
    campusName: conversation.campusName,
    direction: 'parent_to_centre',
    actorRole: 'parent',
    actorName: displayNameFromHeader_(message.getFrom()) || conversation.parentName || '',
    fromAddress: sender,
    toAddress: conversation.centreInbox,
    subjectLine: baseSubjectV3_(conversation.subjectLine || message.getSubject()),
    messageText: body,
    gmailMessageId: message.getId(),
    gmailThreadId: thread.getId(),
    sourceMessageId: message.getId(),
    sendStatus: 'received_and_forwarded',
    attachmentNames,
    timestamp: message.getDate().toISOString(),
  });

  const mirrorInternetMessageId = ensureCentreMirrorV3_(cfg, relayToken, conversation);
  const centreDisplayName = parentViaCentreNameV3_(conversation, message);
  const subject = `Re: ${baseSubjectV3_(conversation.subjectLine || message.getSubject())}`;

  sendRawCentreMessageV3_({
    fromAddress: conversation.fromAddress,
    fromName: centreDisplayName,
    toAddress: conversation.centreInbox,
    replyTo: relayAddress,
    subject,
    body,
    inReplyTo: mirrorInternetMessageId,
    references: mirrorInternetMessageId,
    attachments,
  });
}

function ensureCentreMirrorV3_(cfg, relayToken, conversation) {
  cleanupCentreMirrorPropertiesV3_();

  const propertyKey = centreMirrorPropertyKeyV3_(conversation.conversationId);
  const properties = PropertiesService.getScriptProperties();
  const existing = parseCentreMirrorPropertyV3_(properties.getProperty(propertyKey));
  if (existing.messageId) return existing.messageId;

  if (!conversation.messageText) {
    throw new Error('The original feedback body is unavailable, so the centre Gmail thread cannot be created safely.');
  }

  assertSenderAliasV3_(conversation.fromAddress);

  const relayAddress = `reply+${relayToken}@${cfg.relayDomain}`;
  const parentLabel = [conversation.parentName, conversation.parentEmail ? `<${conversation.parentEmail}>` : '']
    .filter(Boolean)
    .join(' ')
    .trim();
  const contextLine = parentLabel ? `Original feedback sent to ${parentLabel}` : 'Original feedback';
  const mirrorBody = `${contextLine}\n\n${String(conversation.messageText || '').trim()}`;
  const desiredMessageId = `<st-centre-${String(conversation.conversationId).replace(/[^A-Za-z0-9._-]/g, '')}@${cfg.relayDomain}>`;

  const sent = sendRawCentreMessageV3_({
    fromAddress: conversation.fromAddress,
    fromName: conversation.fromName || conversation.campusName || 'Success Tutoring',
    toAddress: conversation.centreInbox,
    replyTo: relayAddress,
    subject: baseSubjectV3_(conversation.subjectLine),
    body: mirrorBody,
    messageId: desiredMessageId,
    attachments: [],
  });

  const actualMessageId = internetMessageIdForGmailMessageV3_(sent.id) || desiredMessageId;
  properties.setProperty(propertyKey, JSON.stringify({
    messageId: actualMessageId,
    createdAt: Date.now(),
  }));

  console.log(`Created centre mirror for conversation ${conversation.conversationId}: ${actualMessageId}`);
  return actualMessageId;
}

function sendRawCentreMessageV3_(options) {
  verifyGmailAdvancedServiceV3_();
  assertSenderAliasV3_(options.fromAddress);

  const rawMime = buildRawMimeV3_(options);
  const encoded = Utilities.base64EncodeWebSafe(rawMime, Utilities.Charset.UTF_8).replace(/=+$/g, '');
  const sent = Gmail.Users.Messages.send({ raw: encoded }, 'me');
  if (!sent || !sent.id) throw new Error('Gmail API did not return a sent message id.');
  return sent;
}

function internetMessageIdForGmailMessageV3_(gmailMessageId) {
  verifyGmailAdvancedServiceV3_();
  const message = Gmail.Users.Messages.get('me', gmailMessageId, {
    format: 'metadata',
    metadataHeaders: ['Message-ID'],
  });
  const headers = message && message.payload && message.payload.headers ? message.payload.headers : [];
  for (const header of headers) {
    if (String(header.name || '').toLowerCase() === 'message-id') {
      return normaliseInternetMessageIdV3_(header.value);
    }
  }
  return '';
}

function buildRawMimeV3_(options) {
  const fromAddress = safeAddressV3_(options.fromAddress);
  const toAddress = safeAddressV3_(options.toAddress);
  const replyTo = safeAddressV3_(options.replyTo);
  const subject = safeHeaderV3_(options.subject || 'Feedback');
  const fromName = safeHeaderV3_(options.fromName || 'Success Tutoring');
  const body = String(options.body || '').replace(/\r\n?/g, '\n');
  const attachments = Array.isArray(options.attachments) ? options.attachments : [];

  const headers = [
    `From: ${mimeMailboxV3_(fromName, fromAddress)}`,
    `To: ${toAddress}`,
    `Reply-To: ${replyTo}`,
    `Subject: ${mimeWordV3_(subject)}`,
  ];

  const messageId = normaliseInternetMessageIdV3_(options.messageId);
  const inReplyTo = normaliseInternetMessageIdV3_(options.inReplyTo);
  const references = normaliseInternetMessageIdV3_(options.references);
  if (messageId) headers.push(`Message-ID: ${messageId}`);
  if (inReplyTo) headers.push(`In-Reply-To: ${inReplyTo}`);
  if (references) headers.push(`References: ${references}`);
  headers.push('MIME-Version: 1.0');

  if (!attachments.length) {
    headers.push('Content-Type: text/plain; charset="UTF-8"');
    headers.push('Content-Transfer-Encoding: base64');
    return `${headers.join('\r\n')}\r\n\r\n${base64LinesV3_(body)}\r\n`;
  }

  const boundary = `=_ST_RELAY_V3_${Utilities.getUuid().replace(/-/g, '')}`;
  headers.push(`Content-Type: multipart/mixed; boundary="${boundary}"`);

  const parts = [
    `${headers.join('\r\n')}\r\n\r\n`,
    `--${boundary}\r\n`,
    'Content-Type: text/plain; charset="UTF-8"\r\n',
    'Content-Transfer-Encoding: base64\r\n\r\n',
    `${base64LinesV3_(body)}\r\n`,
  ];

  attachments.forEach((attachment) => {
    const contentType = safeHeaderV3_(attachment.getContentType() || 'application/octet-stream');
    const originalName = String(attachment.getName() || 'attachment').replace(/[\r\n]/g, ' ').trim();
    const safeName = originalName.replace(/["\\]/g, '_').slice(0, 180) || 'attachment';
    parts.push(`--${boundary}\r\n`);
    parts.push(`Content-Type: ${contentType}; name="${safeName}"\r\n`);
    parts.push('Content-Transfer-Encoding: base64\r\n');
    parts.push(`Content-Disposition: attachment; filename="${safeName}"\r\n\r\n`);
    parts.push(`${wrapBase64V3_(Utilities.base64Encode(attachment.getBytes()))}\r\n`);
  });

  parts.push(`--${boundary}--\r\n`);
  return parts.join('');
}

function cleanReplyBodyV3_(rawBody) {
  let body = String(rawBody || '')
    .replace(/\r\n?/g, '\n')
    .replace(/\u00a0/g, ' ')
    .trim();
  if (!body) return '';

  body = body.replace(/^.{1,220}?\s+replied to the feedback email\.\s*\n+/i, '');

  const splitPatterns = [
    /\n\s*-{3,}\s*\n\s*Original subject:/i,
    /\n\s*Reply normally to this email\.[\s\S]*$/i,
    /\n\s*On[\s\S]{0,1200}?\bwrote:\s*(?:\n|$)/i,
    /\n\s*-{2,}\s*Original Message\s*-{2,}[\s\S]*$/i,
    /\n\s*From:\s*[^\n]+\n\s*(?:Sent|Date):\s*[^\n]+\n\s*To:\s*[^\n]+\n\s*Subject:\s*[^\n]+/i,
    /\n\s*_{5,}\s*\n/,
  ];

  let cut = -1;
  splitPatterns.forEach((pattern) => {
    const index = body.search(pattern);
    if (index >= 0 && (cut < 0 || index < cut)) cut = index;
  });
  if (cut >= 0) body = body.slice(0, cut).trim();

  return body
    .split('\n')
    .filter((line) => !/^\s*>/.test(line))
    .join('\n')
    .replace(/<https?:\/\/[^>\s]{180,}>/gi, '')
    .replace(/https?:\/\/\S{250,}/gi, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function baseSubjectV3_(value) {
  let subject = String(value || 'Feedback')
    .replace(/\[ST-RELAY:[^\]]+\]\s*/ig, '')
    .replace(/[\r\n]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  let previous = '';
  while (subject && subject !== previous) {
    previous = subject;
    subject = subject.replace(/^(?:re|fw|fwd)\s*:\s*/i, '').trim();
  }
  return (subject || 'Feedback').slice(0, 240);
}

function parentViaCentreNameV3_(conversation, message) {
  const parent = displayNameFromHeader_(message.getFrom()) || conversation.parentName || conversation.parentEmail || 'Parent';
  const centre = conversation.fromName || conversation.campusName || 'Success Tutoring';
  return `${parent} via ${centre}`.slice(0, 100);
}

function assertSenderAliasV3_(fromAddress) {
  const from = String(fromAddress || '').toLowerCase();
  if (!from) throw new Error('The centre sender address is missing.');
  const primary = String(Session.getActiveUser().getEmail() || '').toLowerCase();
  if (from === primary) return;
  const aliases = GmailApp.getAliases().map((value) => String(value || '').toLowerCase());
  if (!aliases.includes(from)) throw new Error(`Configured sender ${from} is not available as a Gmail alias.`);
}

function verifyGmailAdvancedServiceV3_() {
  if (typeof Gmail === 'undefined' || !Gmail.Users || !Gmail.Users.Messages) {
    throw new Error('Gmail API service is not enabled. In Apps Script, click + beside Services, add Gmail API v1, then run verifyThreadedRelayV3 again.');
  }
}

function centreMirrorPropertyKeyV3_(conversationId) {
  return `${ST_RELAY_V3_MIRROR_PREFIX}${String(conversationId || '').replace(/[^A-Za-z0-9_-]/g, '')}`;
}

function parseCentreMirrorPropertyV3_(raw) {
  try {
    const parsed = JSON.parse(String(raw || '{}'));
    return {
      messageId: normaliseInternetMessageIdV3_(parsed.messageId),
      createdAt: Number(parsed.createdAt || 0),
    };
  } catch (_) {
    return { messageId: '', createdAt: 0 };
  }
}

function cleanupCentreMirrorPropertiesV3_() {
  const properties = PropertiesService.getScriptProperties();
  const all = properties.getProperties();
  const cutoff = Date.now() - ST_RELAY_V3_MIRROR_MAX_AGE_MS;
  Object.keys(all).forEach((key) => {
    if (!key.startsWith(ST_RELAY_V3_MIRROR_PREFIX)) return;
    const parsed = parseCentreMirrorPropertyV3_(all[key]);
    if (!parsed.createdAt || parsed.createdAt < cutoff) properties.deleteProperty(key);
  });
}

function normaliseInternetMessageIdV3_(value) {
  const clean = safeHeaderV3_(value || '').replace(/^<|>$/g, '').trim();
  if (!clean || !clean.includes('@')) return '';
  return `<${clean}>`;
}

function safeHeaderV3_(value) {
  return String(value || '').replace(/[\r\n]+/g, ' ').trim();
}

function safeAddressV3_(value) {
  const clean = safeHeaderV3_(value).toLowerCase();
  if (!/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(clean)) throw new Error(`Invalid email address: ${clean || '(blank)'}`);
  return clean;
}

function mimeMailboxV3_(name, address) {
  return `${mimeWordV3_(name || 'Success Tutoring')} <${address}>`;
}

function mimeWordV3_(value) {
  const clean = safeHeaderV3_(value);
  if (/^[\x20-\x7E]*$/.test(clean)) return clean;
  return `=?UTF-8?B?${Utilities.base64Encode(clean, Utilities.Charset.UTF_8)}?=`;
}

function base64LinesV3_(value) {
  return wrapBase64V3_(Utilities.base64Encode(String(value || ''), Utilities.Charset.UTF_8));
}

function wrapBase64V3_(value) {
  const clean = String(value || '').replace(/\s+/g, '');
  const lines = [];
  for (let index = 0; index < clean.length; index += 76) lines.push(clean.slice(index, index + 76));
  return lines.join('\r\n');
}

function runReplyRelayV3FastA() {
  runReplyRelayV3Locked_('A');
}

function runReplyRelayV3FastB() {
  runReplyRelayV3Locked_('B');
}

function runReplyRelayV3Locked_(source) {
  const lock = LockService.getScriptLock();
  if (!lock.tryLock(3000)) {
    console.log(`Relay V3 ${source}: skipped because another scan is running.`);
    return;
  }
  const startedAt = Date.now();
  try {
    runReplyRelayV3();
    console.log(`Relay V3 ${source}: completed in ${Date.now() - startedAt}ms.`);
  } finally {
    lock.releaseLock();
  }
}

function verifyThreadedRelayV3() {
  verifyGmailAdvancedServiceV3_();
  if (typeof handleCentreReplyV2_ !== 'function') {
    throw new Error('ScannerV2.gs is missing or outdated. The V3 relay uses its proven centre-to-parent delivery helper.');
  }

  const testId = '<original-test@st-feedback.site>';
  const raw = buildRawMimeV3_({
    fromAddress: 'parramatta@st-feedback.site',
    fromName: 'Kevin Abu via Parramatta Success Tutoring',
    toAddress: 'parramatta@successtutoring.com.au',
    replyTo: 'reply+parramatta-test@st-feedback.site',
    subject: 'Re: Kevin – English • Book Reviews',
    body: 'Parent reply test',
    inReplyTo: testId,
    references: testId,
    attachments: [],
  });

  if (!/In-Reply-To: <original-test@st-feedback\.site>/i.test(raw) ||
      !/References: <original-test@st-feedback\.site>/i.test(raw) ||
      /ST-RELAY:/i.test(raw)) {
    throw new Error('V3 MIME threading self-test failed.');
  }

  const cleaned = cleanReplyBodyV3_("Parent answer\n\nOn Fri, 14 Aug 2026 at 10:34 pm Parramatta Success Tutoring\n<parramatta@st-feedback.site> wrote:\n> Old text");
  if (cleaned !== 'Parent answer') throw new Error(`V3 reply cleaner self-test failed: ${cleaned}`);

  console.log(JSON.stringify({
    ok: true,
    version: ST_RELAY_V3_VERSION,
    gmailApi: true,
    centreReplyHelper: true,
    cleanReplySample: cleaned,
    aliases: GmailApp.getAliases(),
  }, null, 2));
}

function installFastRelayTriggersV3() {
  verifyThreadedRelayV3();

  ScriptApp.getProjectTriggers()
    .filter((trigger) => /^runReplyRelay/.test(trigger.getHandlerFunction()))
    .forEach((trigger) => ScriptApp.deleteTrigger(trigger));

  ScriptApp.newTrigger('runReplyRelayV3FastA').timeBased().everyMinutes(1).create();
  Utilities.sleep(15000);
  ScriptApp.newTrigger('runReplyRelayV3FastB').timeBased().everyMinutes(1).create();

  console.log(`Installed two locked V3 one-minute relay triggers. Version ${ST_RELAY_V3_VERSION}.`);
}

function showRelayTriggersV3() {
  console.log(JSON.stringify({
    version: ST_RELAY_V3_VERSION,
    triggers: ScriptApp.getProjectTriggers().map((trigger) => ({
      functionName: trigger.getHandlerFunction(),
      source: String(trigger.getTriggerSource()),
    })),
  }, null, 2));
}
